### ISSUE TITLE
Template CAPZ objects for worker cluster

### ISSUE THREAD

**Issue by alexeldeib** [juan-lee/carp#12]
Each worker cluster requires several capz objects. Make it easy to template and deploy this in a reconcile loop by adding helper functions.

- [x] KubeadmConfigTemplate
- [x] Cluster - Ace
- [x] KubeadmControlPlane - Ace claimed
- [x] AzureCluster - Shoshana
- [x] MachineDeployment for control plane
- [x] MachineDeployment for worker nodes
- [x] AzureMachineTemplate for control plane
- [x] AzureMachineTemplate for control plane

**Comment by shanalily** [comment]
I can do AzureCluster and both MachineDeployments.

**Comment by alexeldeib** [comment]
Nice! I'll start assembling pieces in a reconcile loop
